# Project information
site_name: Guartinel Docs
site_description: The remote monitoring system documentation
site_author: Sysment Kft.
site_url: https://guartinel.com

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 Sysment Kft.'
    
theme:
    name: material
    language: 'en'

extra:
  palette:
    primary: 'blue'
    accent:  'light-blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:

extra_javascript:

docs_dir: './docs'

nav:
- Home: index.md
- Packages: packages.md
- Alert : alert.md
- API: api.md
- CLI: cli.md